name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: List files before
        run: find .
      - name: Generate keystore 1
        run: keytool -genkeypair -v -keystore your-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias your-key-alias -storepass your-store-password -keypass your-key-password -dname "CN=Your Name, OU=Your Organization, O=Your Company, L=Your City, S=Your State, C=Your Country"
      - name: Generate keystore 2
        run: keytool -noprompt -genkey -v -keystore app.keystore -storepass storepassjustfortestingshouldbesecret -alias release-key -keypass keypassjustfortestingshouldbesecret -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Your Name, OU=Your Organization, O=Your Company, L=Your City, S=Your State, C=Your Country"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: List files after
        run: find .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-ubuntu
          path: app/build/outputs/apk/release/app-release-unsigned.apk
