name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: List files before
        shell: cmd
        run: dir /b /s
      - name: Build with Gradle
        shell: cmd
        run: gradlew.bat build --no-daemon
      - name: List files after
        shell: pwsh
        run: (Get-ChildItem -Recurse).FullName
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: app/build/outputs/apk/release/app-release-unsigned.apk
